name = "Apollo"
uuid = "a930802f-a247-437b-b6f0-df19c47a5315"
authors = ["Joshua Billson"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
